title: Hero
status: wip
context:
    hero:
        title: "Hero title"
        content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Hic dicta ratione ut debitis illo minima ipsam nulla. Magnam, voluptates, eos."